version: '3.8'

services:
  app:
    build: .
    ports:
      - "5080:5080"
    environment:
      FLASK_ENV: development
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: cmsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alsen#211
    ports:
      - "5432:5432"