version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_NAME: cmsdb
      DB_USER: postgres
      DB_PASSWORD: Alsen#211
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cmsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alsen#211
    ports:
      - "5432:5432"
